### ISSUE TITLE
problem with tex-live build on travis-ci

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf-standard#119]
The Travis error is 

```
(/home/travis/build/spacetelescope/asdf-standard/texlive/texmf-dist/tex/latex/h
yperref/hpdftex.def
(/home/travis/build/spacetelescope/asdf-standard/texlive/texmf-dist/tex/latex/o
berdiek/rerunfilecheck.sty))
(/home/travis/build/spacetelescope/asdf-standard/texlive/texmf-dist/tex/latex/o
berdiek/hypcap.sty)
(/home/travis/build/spacetelescope/asdf-standard/texlive/texmf-dist/tex/latex/c
aption/newfloat.sty)
! LaTeX Error: File `capt-of.sty' not found.
```

**Comment by benyomin** [comment]
what's the fix, have to copy this .sty to the directory??
me too, same error. (https://travis-ci.org/benyomin/benyomin.github.io/builds/159266677)

**Comment by benyomin** [comment]
found file `(/usr/local/texlive/2016/texmf-dist/tex/latex/capt-of/capt-of.sty
Package: capt-of 2009/12/29 v0.2 standard captions outside of floats`. 
I think that I can copy it to the travis-ci directory and fix the problem

**Comment by justincely** [comment]
Since we've moved the docs fully to RTD, we no longer need the texlive build process.  It's since been removed, so this is no longer an issue.
