### ISSUE TITLE
Top-level schema and test files

### ISSUE THREAD

**Issue by eschnett** [spacetelescope/asdf-standard#163]
The standard defines for the top-level schema `core/asdf-1.0.0` the keys
- asdf_library
- history
- data
- fits
- wcs

Some of the test files contain additional properties; e.g. `compressed.yaml` contains `bzp2` and `zlib`.

Does a library need to handle arbitrary properties with unknown keys? Can it make any assumptions, e.g. that they will only contain `ndarray`s?

**Comment by drdavella** [comment]
Hi @eschnett, thanks for your question and your interest in ASDF.

You probably want to look at the latest version of the top-level schema, which is `core/asdf-1.1.0`. The restrictions on `data`, `wcs`, and `fits` have been removed.

And yes, any implementation must be able to handle arbitrary properties at the top level. This is expressed by the following property:
https://github.com/spacetelescope/asdf-standard/blob/c3e5a36006bd72b570ae6944a59e85ef3a23b9d8/schemas/stsci.edu/asdf/core/asdf-1.1.0.yaml#L33

This allows users to represent their data in any way they see fit. No assumptions are made about the types of properties at the top level. However, the restrictions on `asdf_library` and `history` must be respected.

Just out of curiosity, but what motivates your interest in the ASDF Standard? Do you plan to develop a new implementation of ASDF? You should note that the documentation is somewhat out of date and may be incomplete in some ways, but suggestions and/or contributions you can provide are welcome.

**Comment by eschnett** [comment]
I was looking at https://asdf-standard.readthedocs.io/en/latest/index.html, which doesn't point to this new version of the `asdf` schema yet.

I am evaluating ASDF as file format for the Einstein Toolkit https://einsteintoolkit.org. We are currently using HDF5, and we find that certain operations are quite slow. The simplicity of ASDF might give us greater control and thus might enable us to improve performance. My current ASDF sandbox is at https://github.com/eschnett/asdf-cxx .

**Comment by drdavella** [comment]
That's great that you are interested in ASDF! Again, I apologize for the standard docs being a bit out of date.

Also that's great that you are working on a C++ implementation of ASDF. Any feedback you have about the standard after working on this implementation would be greatly appreciated. I am also making (somewhat slow) progress on a C++ implementation myself, and once it's in a more complete state, it might be useful to compare and to see if we could potentially converge.

**Comment by eschnett** [comment]
I'd be very interested in converging.
