### ISSUE TITLE
Error in reference example

### ISSUE THREAD

**Issue by eschnett** [spacetelescope/asdf-standard#165]
Tree references as described on <https://asdf-standard.readthedocs.io/en/latest/tree.html#references> show this example, which is wrong:
```
reference_data:
  $ref: "http://www.nowhere.com/reference.asdf#wavelengths/0"
```

According to the JSON standard defining URI references, the URI fragment (the part after the hash sign `#`) needs to start with a slash `/`. The second example shown is correct in this respect.

**Comment by drdavella** [comment]
@eschnett thank you for the feedback. Do you have a specific reference for this requirement so that I can confirm before making the change?

**Comment by eschnett** [comment]
@drdavella The references I checked were the RFCs defining the JSON pointer <https://tools.ietf.org/html/rfc6901> and the generic URL definition <https://tools.ietf.org/html/rfc3986>.
