### ISSUE TITLE
Determine use of propertyOrder

### ISSUE THREAD

**Issue by embray** [spacetelescope/asdf-standard#37]
In "Extending ASDF" there is a "TBD" note on the necessity of the propertyOrder keyword in YAML Schema.  I don't thing that needs to be determined right now, but I thought I would open an issue to track/discuss it.

I would argue that it is at least _useful_, informationally if nothing else.  Ordered mappings are, I think, a useful data structure to be able to validate (regardless of how it's serialized--for example even if it's treated equivalently to an array of ordered pairs).  propertyOrder could also be considered a complement to the "items" keyword associated with arrays.

One thing that might be worth doing is softening it somewhat by including a "strict" flag to it--by default propertyOrder would not be strict, and would just be a suggestion (validation would not fail, but perhaps a warning would be recorded).  But if it is made strict then validation would fail outright.  None of the ASDF core data structures should use propertyOrder strictly in my opinion, but I think it's worth having the option.

**Comment by embray** [comment]
I added a little bit more about this in the YAML Schema draft I'm working on (still very rough).  But the idea is that we would recommend that validators check this when possible, but that it should not be relied on, and that data structures that *require* a property order to be correctly interpreted should also write out the property order as an array.

However, it would also be recommended that propertyOrder be used as a presentation hint when writing YAML documents--giving a preferred order for writing out the properties of a particular object.

**Comment by drdavella** [comment]
Closing since `propertyOrder` is supported by ASDF.
