### ISSUE TITLE
Multi-resolution support

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf-standard#5]
FADF Paper I says: "A reasonable framework should be able to support multiple representations of the same data (e.g. multiple resolutions or fidelities) preferably from a single master file".

At it's most basic, this should be easy to do with the right conventions for it, but, as always, the devil is in the details.

**Comment by drdavella** [comment]
There is nothing in the file format that prevents users from encoding this information. It does not seem to require specific language in the standard. Perhaps it could be encoded in a higher level schema library, like the one being developed by @perrygreenfield.
