### ISSUE TITLE
Use JSON Pointer syntax in YAML aliases

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf-standard#51]
In an email discussion, @embray suggested that if JSON Pointers were put in YAML aliases, they may not require an anchor at the other end, and we may get some of the flexibility of JSON Pointer with the syntax of YAML aliases.

Let this be a thread to discuss that further...

**Comment by embray** [comment]
This was a very half-baked thought, but I'd like to at least look into it.  Maybe it's not worth the trouble, or maybe it could be really slick...
