### ISSUE TITLE
modify and append blocks to file

### ISSUE THREAD

**Issue by migueldvb** [spacetelescope/asdf-standard#64]
It is not completely clear if the layout allows to extend a dataset in a single self-contained file by modifying blocks and appending new blocks without rewriting the entire file. We are interested in an application that requires appending new data by updating the tree which could have empty space before the start of the blocks, and appending data to unused space in blocks and new binary blocks at the end. Cuold this write operations be done at end-of-file in single-file mode without rewriting the entire file?

**Comment by mdboom** [comment]
Yes.  This is an explicit part of the design, and is already implemented in pyasdf in the `update` command.

So I guess the question is -- where were you expecting to find this information and didn't?  It's mentioned twice in the "file layout" chapter.

**Comment by migueldvb** [comment]
OK, thanks. I was not sure if this information in the file layout
description refers to the single-file or multiple-file forms. Perhaps it
could be useful to say that it applies to both of them.
