### ISSUE TITLE
Should be more specific about precision of numeric literals in tree

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf-standard#88]
Reading of numeric literals in YAML happens differently in different YAML parser implementations.

For example: PyYAML will parse an arbitrary length integer into a Python long, so they are truly arbitrary-sized integers.  js-yaml, however, parses into a float64, since everything is a float64 in JavaScript.  Reading a file produced by Python into Javascript would result in unexpected data loss.  To be truly portable, an integer should use no more than 52 significant bits (since that's the size of the significand in a double).

There's potential differences with floating-point numbers as well, though everything I've tried seems to be float64/double.  (The YAML spec seems to be silent on this, AFAICT).  But as hinted in #20 and for the time specification, it would be nice if this supported quad precision someday if possible.

So what should the spec say about this?  That the significant bits should be no more than 52?  (Meaning trying to write out a large integer from Python would raise an exception).  Or should it just be a recommendation (meaning perhaps a warning about this when writing out a large integer).  Or, we could explicitly say integers are arbitrary length, in which case languages that don't currently parse YAML that way would be forced to grow such a feature to be truly ASDF compliant.

- [ ] Add a reference file test with large integer and floating-point literals

Cc: @embray, any thoughts?

Related to #20.

**Comment by embray** [comment]
I wonder how different FITS readers/writers handle this.  The FITS spec is also pretty light on details of what to do here.  For example it doesn't forbid arbitrary-length integers, and doesn't say what to do on platforms that can't read those values into native int types (though I need to double check exactly what it says...or doesn't say as the case may be).

I'd lean on the side of flexibility, perhaps with appropriate warnings?

**Comment by mdboom** [comment]
I'm still not sure how to address this one (but I'd like to for 1.0).  For maximum portability, I think we have to say that YAML literal numbers are 64-bit double floats.  Anything more and you create a file that may not be readable in all tools (though it seems unfortunate to limit something that would otherwise work when staying within the Python world).

**Comment by embray** [comment]
Yeah, it's too bad, but I think for now more restriction is better.  It'll be easier to add later than to remove.
