### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by embray** [spacetelescope/asdf-standard#97]
Question 1: Why not "just" use HDF5?

I could probably think of a few others too, such as "Why don't you have parallel I/O?" and things like that.

Should probably link to it from pyasdf as well.  I don't think pyasdf needs a FAQ yet because (and you can correct me on this) I don't think pyasdf has enough users for there to be actual FAQs yet :)

**Comment by justincely** [comment]
@embray, i've pulled together the wiki for this repo to support some of this; and i've put a quick FAQ page as well.  I figure that can serve to collect/distribute info until there's enough sections to maybe include in the actual documentation.  

Thoughts?

**Comment by nden** [comment]
An FAQ page is on the wiki.
